// src/routes/(app)/login/+page.svelte
<script lang="ts">
	import { instanceOf } from '~/lib/utils';
	import LL from '~/i18n/i18n-svelte';
	import Button from '~/lib/components/PrimaryButton.svelte';
	import Input from '~/lib/components/Input.svelte';
	import type { ApiDataResponse, ApiResponse } from '~/lib/models/api-response';
	import { fly } from 'svelte/transition';
	import { quadOut } from 'svelte/easing';
	import Spinner from '~/lib/components/Spinner.svelte';
	import { ApiRoutes } from '~/lib/utils/api-routes';
	import { onMount } from 'svelte';
	import { z } from 'zod';
	import { goto } from '$app/navigation';
	import type { PageData } from './$types';
	import SecondaryButton from '~/lib/components/SecondaryButton.svelte';
	import LogoType from '~/lib/components/LogoType.svelte';
	import Link from '~/lib/components/Link.svelte';
	import type User from '~/lib/models/user';
	import Icon from '~/lib/components/Icon.svelte';

	type FormFields = 'email' | 'password';

	export let data: PageData;
	let logging = false;
	let canSubmit = false;
	let fieldErrors: Partial<Record<FormFields, string>> = {};
	let formResponse: ApiResponse | undefined;
	const inputElements: Record<FormFields, HTMLInputElement> = {} as any;

	onMount(() => {
		canSubmit = true;
	});

	async function submit(this: HTMLFormElement) {
		logging = true;
		formResponse = undefined;

		const data = new FormData(this);
		const schema = z.object({
			email: z.string().trim().email($LL.login.email.regex()),
			password: z.string().nonempty($LL.login.password.empty())
		});

		const result = await schema.safeParseAsync({
			email: data.get('email'),
			password: data.get('password')
		});
		if (!result.success) {
			fieldErrors = {};
			result.error.issues.forEach((iss) => {
				fieldErrors[iss.path[0] as FormFields] = iss.message;
			});
			inputElements[result.error.issues[0].path[0] as FormFields].focus();
			logging = false;
			return;
		}

		fieldErrors = {};
		data.set('email', result.data.email);
		const json = await fetch(this.action, {
			method: 'post',
			body: data
		})
			.then((v) => v.json())
			.finally(() => {
				logging = false;
			});

		formResponse = json;
		if (instanceOf<ApiDataResponse<User>>(json, 'data')) {
			canSubmit = false;
			goto('/dashboard');
		}
	}
</script>

{#if data.user}
	<section class="mx-auto w-fit mt-48 text-center">
		<h1 class="uppercase text-h1 text-8xl text-primary-700">{$LL.login.oops()}</h1>
		<h3 class="mt-4">{$LL.login.alreadyLoggedIn()}</h3>
		<div class="mt-4">
			<Link href="/">
				<Button type="button">{$LL.login.back()}</Button>
			</Link>
			<Link href="/logout" class="ml-4">
				<SecondaryButton type="button">{$LL.login.logout()}</SecondaryButton>
			</Link>
		</div>
	</section>
{:else}
	<div class="w-max mx-auto">
		<LogoType class="mt-16" fill="fill-primary-700" />
		<h3 class="text-center mt-6 text-fill-600">{$LL.login.header()}</h3>
		<div class="mx-auto w-min mt-4">
			<form
				class="text-left flex flex-col gap-y-6 min-w-[400px] bg-fill-100 border-fill-300 border-[1px] rounded-lg p-4"
				method="post"
				action={ApiRoutes.LOGIN}
				on:submit|preventDefault={submit}
			>
				<div class="flex flex-col gap-y-1">
					<Input
						bind:input={inputElements.email}
						id="email"
						name="email"
						type="email"
						spellcheck={false}
						novalidate="true"
						placeholder={$LL.login.email.placeholder()}
						label={$LL.login.email.label()}
						caption={fieldErrors?.email}
						accent={fieldErrors?.email ? 'negative' : undefined}
					/>
				</div>
				<div class="flex flex-col gap-y-1 relative">
					<Link href="/reset-password" class="absolute right-0 top-0">
						{$LL.login.forgotPassword()}
					</Link>
					<Input
						bind:input={inputElements.password}
						id="password"
						name="password"
						type="password"
						placeholder={$LL.login.password.placeholder()}
						class="transition"
						label={$LL.login.password.label()}
						caption={fieldErrors?.password}
						accent={fieldErrors?.password ? 'negative' : undefined}
					/>
				</div>
				<Button type="submit" class="w-max" disabled={!canSubmit || logging}>
					<div class="flex gap-x-3 items-center">
						<div class="w-6 h-6 relative overflow-hidden">
							<div
								class="absolute transition duration-200 ease-in-out {!logging
									? 'scale-0 opacity-0'
									: ''}"
							>
								<Spinner class="w-full h-full" />
							</div>
							<Icon
								name="ArrowRightOnRectangle"
								class="transition duration-200 text-icon-base ease-in-out {logging
									? 'scale-0 opacity-0'
									: ''}"
							/>
						</div>
						{$LL.login.login()}
					</div>
				</Button>
			</form>
			<div class="bg-fill-200/20 border-fill-300 border-[1px] rounded-md p-4 mt-4">
				<span>{$LL.login.noAccount()}</span>{' '}
				<Link href="/signup">{$LL.login.signUp()}</Link>.
			</div>

			{#if formResponse}
				<div transition:fly={{ y: 20, easing: quadOut, duration: 200 }}>
					{#if instanceOf(formResponse, 'error')}
						<div
							class={`border-[1px] rounded-md p-4 mt-4 bg-negative-200 border-negative-400`}
						>
							<p>
								<span class="text-negative-700 text-h5">
									{formResponse.error.code}
								</span>{' '}
								{formResponse.error.message}.
							</p>
						</div>
					{:else}
						<div
							class={`border-[1px] rounded-md p-4 mt-4 bg-positive-200 border-positive-400`}
						>
							<p>
								<span class="text-positive-700 text-h5"> 200 </span>{' '}
								{$LL.login.success()}.
							</p>
						</div>
					{/if}
				</div>
			{/if}
		</div>
	</div>
{/if}

// src/routes/login.tsx
import { createSignal, Show } from 'solid-js';
import { A, createRouteAction } from 'solid-start';
import Button from '~/components/Button';
import { useI18nContext } from '~/components/I18nProvider';
import SpinnerPending from '~/components/SpinnerPending';
import { z } from 'zod';
import Input from '~/components/Input';
import { APIErrorResponse, APIResponse } from '~/models/api-response';
import { instanceOf } from '~/utils';

type FormFields = 'username' | 'password';

export default () => {
	const [t] = useI18nContext();
	const [logging, setLogging] = createSignal(false);
	const [fieldErrors, setFieldErrors] = createSignal<
		Partial<Record<FormFields, string[] | null>>
	>({});
	const [formError, setFormError] = createSignal<
		APIErrorResponse['error'] | undefined
	>();
	const [_, { Form }] = createRouteAction(async (formData: FormData) => {
		setLogging(true);

		const schema = z.object({
			username: z.coerce
				.string()
				.trim()
				.min(3, t.login.username.min({ length: 3 }))
				.regex(/[a-zA-Z0-9]+/, t.login.username.regex()),
			password: z.coerce
				.string()
				.min(3, t.login.password.min({ length: 6 })),
		});
		const ret = await schema.safeParseAsync({
			username: formData.get('username'),
			password: formData.get('password'),
		});

		if (!ret.success) {
			setFieldErrors(ret.error.formErrors.fieldErrors);
			setLogging(false);
			return;
		}

		setFieldErrors({});
		formData.set('username', ret.data.username);

		const json = await fetch('/api/v1/login', {
			method: 'post',
			body: formData,
		})
			.then((v) => v.json() as Promise<APIResponse>)
			.finally(() => {
				setLogging(false);
			});

		if (instanceOf<APIErrorResponse>(json, 'error')) {
			setFormError(json.error);
			return;
		}
		setFormError();
	});
	return (
		<>
			<h1 class="text-center mx-auto mt-24">{t.login.header()}</h1>
			<div class="mx-auto w-min mt-6">
				<Form
					class="flex flex-col gap-y-6 min-w-[400px]
					bg-fill-100 border-fill-300 border-[1px] rounded-lg p-4 mt-8"
				>
					<div class="flex flex-col gap-y-1">
						<Input
							id="username"
							name="username"
							type="text"
							spellcheck={false}
							placeholder={t.login.username.placeholder()}
							class="transition"
							label={t.login.username.label()}
							accent={
								fieldErrors().username?.[0]
									? 'negative'
									: undefined
							}
							caption={fieldErrors().username?.[0]}
						/>
					</div>
					<div class="flex flex-col gap-y-1 relative">
						<a href="#" class="absolute right-0 top-0">
							{t.login.forgotPassword()}
						</a>
						<Input
							id="password"
							name="password"
							type="password"
							placeholder={t.login.password.placeholder()}
							class="transition"
							label={t.login.password.label()}
							accent={
								fieldErrors().password?.[0]
									? 'negative'
									: undefined
							}
							caption={fieldErrors().password?.[0]}
						/>
					</div>
					<Button type="submit" disabled={logging()}>
						<SpinnerPending when={logging}>
							{t.login.login()}
						</SpinnerPending>
					</Button>
				</Form>
				<div class="bg-fill-200/20 border-fill-300 border-[1px] rounded-md p-4 mt-4">
					<span>{t.login.noAccount()}</span>{' '}
					<A href="/signup">{t.login.signUp()}</A>.
				</div>
				<Show when={!!formError()}>
					<div class="bg-negative-300 border-negative-400 border-[1px] rounded-md p-4 mt-4">
						<p>
							<span class="text-negative-700 text-h5">
								{formError()!.code}
							</span>{' '}
							{formError()!.message}.
						</p>
					</div>
				</Show>
			</div>
		</>
	);
};
